#!/bin/bash


# --pkg lua
valac --disable-warnings --fatal-warnings \
 --pkg gtk+-3.0 --pkg gee-0.8 \
 util.vala \
 child_process.vala \
 EventEmitter.vala \
 MainWindow.vala \
 MainHeaderBar.vala \
 MainMenu.vala \
 SearchGrid.vala \
 ViewGrid.vala \
 ListView.vala \
 ListViewColumn.vala \
 StatusGrid.vala \
 SearchEngine.vala \
 FileProps.vala \
 main.vala \
 -o "./dist/Anything in Linux" && "./dist/Anything in Linux"

 # Application.vala \
 # util.vala app.vala main.vala \
# --pkg glib-2.0
# util.vala main.vala \
